repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev:  v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-added-large-files
    - id: end-of-file-fixer

- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: isort
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: black
    types: [python]

  - id: mypy
    name: mypy
    stages: [commit]
    language: system
    entry: mypy
    types: [python]
    require_serial: true

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: flake8
    types: [python]
    exclude: setup.py

  # - id: pytest
  #   name: pytest
  #   stages: [commit]
  #   language: system
  #   entry: pytest --cov-config=.coveragerc --cov=ppt
  #   types: [python]
  #   pass_filenames: false


- repo: https://github.com/nbQA-dev/nbQA
  rev: 0.4.0
  hooks:
  - id: nbqa-black
    args: ["--nbqa-mutate"]
    additional_dependencies: [black==20.8b1]
  - id: nbqa-isort
    args: ["--nbqa-mutate", "--nbqa-config=setup.cfg", "-p=sktime"]
    additional_dependencies: [isort==5.6.4]
  - id: nbqa-flake8
    args: ["--nbqa-config=setup.cfg", "--extend-ignore=E402,E203"]
    additional_dependencies: [flake8==3.8.3]
